import { Inter } from "next/font/google";
import MainHeader from "@/components/main-header";
import styles from "./layout.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <>
          <div className={styles.blur}>{children}</div>
        </>
      </body>
    </html>
  );
}
